# Base node image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install development dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]