version: '3.8'

services:
  app:
    build: .
    container_name: school-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - school-network

  db:
    image: mysql:8.0
    container_name: school-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - school-network

  redis:
    image: redis:alpine
    container_name: school-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - school-network

  nginx:
    image: nginx:alpine
    container_name: school-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - school-network

volumes:
  mysql_data:
  redis_data:

networks:
  school-network:
    driver: bridge